version: '3.8'

services:
  postgres:
    image: postgres
    container_name: my_postgres
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: mysecret_password
      POSTGRES_DB: nest_crud_prisma
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: mysecret_password
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
